version: '3.8'

services:
  # Serviço do PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: bot-sisci-postgres
    environment:
      POSTGRES_DB: suporte_interno
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - bot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço do Bot Discord
  bot:
    build: .
    container_name: bot-sisci
    environment:

      DISCORD_TOKEN: ${DISCORD_TOKEN}
      
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: suporte_interno
      DB_USER: postgres
      DB_PASSWORD: postgres123
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bot-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:

networks:
  bot-network:
    driver: bridge
